// facts.js | The Database of Facts

// Predefined list of facts and their classifications
const factList = {
    "nasa's mars rover successfully lands": "real",
    "aliens found living among us": "fake",
    "stock market hits all-time highs": "real",
    "government declares pizza a vegetable": "fake",
    "new species of fish discovered in amazon": "real",
    "man claims he can talk to animals": "fake",
    "the 2020 U.S. presidential election had the highest voter turnout since 1900": "real",
    "Barack Obama was the first African American president of the United States": "real",
    "the U.S. Senate is made up of 100 members, two from each state": "real",
    "the Electoral College was established in 1787 by the founding fathers": "real",
    "Joe Biden became the 46th president of the United States in January 2021": "real",
    "Donald Trump was impeached twice during his presidency": "real",
    "the first woman to run for president in the U.S. was Victoria Woodhull in 1872": "real",
    "the Voting Rights Act was passed in 1965 to eliminate racial discrimination in voting": "real",
    "Hillary Clinton was the first woman to be nominated for president by a major party in 2016": "real",
    "the U.S. Supreme Court consists of nine justices": "real",
    "the House of Representatives has 435 voting members": "real",
    "California has the highest number of electoral votes, followed by Texas and Florida": "real",
    "the U.S. Constitution was ratified in 1788": "real",
    "the midterm elections occur every four years, halfway through a president's term": "real",
    "the Democratic Party was founded in 1828": "real",
    "the Republican Party was founded in 1854": "real",
    "the first presidential debate was held between John F. Kennedy and Richard Nixon in 1960": "real",
    "in 2022, the U.S. saw the highest number of state-level ballot measures in a decade": "real",
    "Georgia's 2020 election saw record-breaking turnout, particularly among minority voters": "real",
    "the 2016 election was the first time in U.S. history that a candidate won the presidency without winning the popular vote": "real",
    "the U.S. House of Representatives can impeach a president, but the Senate holds the trial": "real",
    "the first election to use the Electoral College system was in 1789": "real",
    "a voter ID law was enacted in many states, sparking debate over voter suppression": "real",
    "in 2020, over 159 million Americans voted in the presidential election": "real",
    "the U.S. has a federal system of government, dividing powers between national and state governments": "real",
    "the 2024 presidential election is set for November 5, 2024": "real",
    "in 2021, President Biden signed the American Rescue Plan to help combat COVID-19 effects": "real",
    "Senators serve six-year terms, while Representatives serve two-year terms": "real",
    "the longest-serving member of Congress in U.S. history was John Dingell, who served for 59 years": "real",
    "the 19th Amendment granted women the right to vote in 1920": "real",
    "the U.S. Supreme Court ruled in 2015 that same-sex marriage is a constitutional right": "real",
    "the U.S. has had a total of 46 presidents, including Joe Biden": "real",
    "the U.S. Senate was designed to represent the states, while the House represents the people": "real",
    "in 2020, there was a significant increase in mail-in voting due to the COVID-19 pandemic": "real",
    "the Federal Election Commission (FEC) oversees campaign finance laws": "real",
    "voter turnout in the U.S. generally increases during presidential election years": "real",
    "the political party that controls the House of Representatives is often referred to as the majority party": "real",
    "in 2018, Democrats regained control of the House of Representatives after losing it in 2016": "real",
    "the U.S. Congress is a bicameral legislature, meaning it has two chambers": "real",
    "in 2020, 90% of eligible voters in the U.S. registered to vote": "fake",
    "the first presidential inauguration took place in 1789 for George Washington": "real",
    "the state of Maine has historically had a strong tradition of independent candidates": "real",
    "the U.S. Constitution has been amended 27 times": "real",
    "New Hampshire holds the first primary election in the U.S. presidential nomination process": "real",
    "the U.S. flag has 50 stars, representing the 50 states": "real",
    "the U.S. has had female governors since the 1970s, with Nellie Tayloe Ross being the first in 1925": "real",
    "the Senate has the power to confirm presidential appointments, including Supreme Court justices": "real",
    "the 2020 election was marked by allegations of widespread voter fraud, which were largely debunked": "real",
    "the 2020 election saw a record number of women and minorities elected to Congress": "real",
    "state laws regarding voting can vary significantly from one state to another": "real",
    "the Republican Party is often associated with conservative policies and principles": "real",
    "the Democratic Party is often associated with liberal policies and principles": "real",
    "in 2022, several states passed laws to limit voting access, citing security concerns": "real",
    "the first presidential election in the U.S. was held in 1788-1789": "real",
    "the state of Texas has the most representatives in the House of Representatives": "real",
    "the 2000 presidential election was decided by a controversial Supreme Court ruling in Bush v. Gore": "real",
    "the U.S. has a history of voter suppression tactics, particularly against minorities": "real",
    "the U.S. Senate is often seen as a more prestigious body compared to the House of Representatives": "real",
    "the Voting Rights Act was reauthorized multiple times, with significant bipartisan support until 2006": "real",
    "the midterm elections can significantly change the balance of power in Congress": "real",
    "the U.S. presidential election process is governed by a combination of federal and state laws": "real",
    "in 2012, the U.S. saw a significant increase in youth voter turnout": "real",
    "the phrase 'we the people' is found in the Preamble of the U.S. Constitution": "real",
    "the Senate Judiciary Committee is responsible for overseeing judicial nominations": "real",
    "Congressional committees play a vital role in the legislative process": "real",
    "the House of Representatives has the sole power to initiate revenue bills": "real",
    "a presidential candidate must be at least 35 years old to run for office": "real",
    "the president can veto legislation passed by Congress": "real",
    "the state of Florida has historically been a key battleground state in presidential elections": "real",
    "the U.S. has a history of third-party candidates influencing election outcomes": "real",
    "the first televised presidential debate was held in 1960 between Kennedy and Nixon": "real",
    "the Electoral College system was designed to balance the influence of populous states with smaller states": "real",
    "in 2020, a record number of ballots were cast during early voting": "real",
    "the state of California passed a law to automatically register voters in 2016": "real",
    "the U.S. Supreme Court can overturn laws passed by Congress": "real",
    "the 2008 financial crisis had a significant impact on the 2008 presidential election": "real",
    "the 2020 election saw a major increase in the use of mail-in ballots due to the pandemic": "real",
    "in 2020, several states adopted ranked-choice voting for elections": "real",
    "the Federal Election Commission (FEC) regulates campaign finance in the U.S.": "real",
    "in 2021, President Biden announced a plan to invest in infrastructure and job creation": "real",
    "the state of New York has historically had a significant impact on presidential primaries": "real",
    "the U.S. political landscape has been increasingly polarized in recent years": "real",
    "the Senate has the power to confirm or deny treaties negotiated by the president": "real",
    "the House of Representatives is often referred to as the lower house of Congress": "real",
    "the 1965 Voting Rights Act aimed to eliminate barriers to voting for African Americans": "real",
    "the U.S. Constitution is the oldest written national constitution still in use": "real",
    "the presidential election occurs on the first Tuesday after the first Monday in November": "real",
    "the state of Pennsylvania has been a critical swing state in several presidential elections": "real",
    "the U.S. has had several political parties throughout its history, including the Federalists and Whigs": "real",
    "the Congressional Budget Office (CBO) provides budgetary and economic analysis to Congress": "real",
    "the U.S. has a system of checks and balances to prevent any one branch of government from becoming too powerful": "real",
    "the 2022 midterms saw a mixed outcome, with Democrats retaining control of the Senate and Republicans taking control of the House": "real",
    "the U.S. military has historically been involved in politics, especially during times of war": "real",
    "the 2024 election cycle is anticipated to feature high-profile candidates from both parties": "real",
    "political action committees (PACs) play a significant role in funding campaigns": "real",
    "the U.S. has seen an increase in political activism, particularly among younger voters": "real",
    "the debate over gerrymandering continues to shape political representation in various states": "real",
    "in 2020, voter registration efforts were heightened, leading to increased participation": "real",
    "the U.S. Supreme Court has ruled on many landmark cases that have shaped civil rights": "real",
    "the Federal Reserve plays a key role in the U.S. economy and can influence election outcomes": "real",
    "the 2020 election was marked by misinformation and disinformation campaigns": "real",
    "many states have adopted measures to make voting more accessible": "real",
    "in recent years, social media has become an influential platform for political campaigning": "real",
    "the U.S. has a long history of political protests and movements advocating for change": "real",
    "the state of Iowa holds the first caucus in the presidential nomination process": "real",
    "the U.S. has experienced a significant rise in voter suppression allegations in recent years": "real",
    "the 2016 election saw the rise of populist movements in both major parties": "real",
    "the United States has a diverse electorate, with varying interests and priorities": "real",
    "the Supreme Court's Citizens United decision in 2010 changed the landscape of campaign finance": "real",
    "in 2020, various organizations worked to combat misinformation in elections": "real",
    "the U.S. has a history of third-party candidates impacting major party platforms": "real",
    "the political climate in the U.S. has become increasingly contentious in recent years": "real",
    "the process of redistricting occurs every ten years after the census": "real",
    "the U.S. has seen a rise in grassroots movements aimed at influencing policy": "real",
    "the U.S. government shutdowns can significantly impact the economy and public services": "real",
    "many states have passed laws requiring photo identification to vote": "real",
    "the concept of federalism allows for varying laws and regulations across states": "real",
    "the 2020 election had significant implications for future U.S. foreign policy": "real",
    "the U.S. has a history of political parties evolving and changing platforms over time": "real",
    "the Democratic National Committee (DNC) and Republican National Committee (RNC) organize party activities and elections": "real",
    "the Electoral College is a controversial system that has been the subject of reform discussions": "real",
    "the U.S. has a rich tradition of civil disobedience and activism in its history": "real",
    "the Voting Rights Act of 1965 was a significant milestone in the civil rights movement": "real",
    "the presidential primary season begins with state caucuses and primaries leading to party conventions": "real",
    "in 2022, numerous ballot measures were proposed on issues like abortion and voting access": "real",
    "the U.S. political system is influenced by lobbyists and interest groups seeking to sway policy": "real",
    "the U.S. Census is conducted every ten years and is crucial for congressional representation": "real",
    "the U.S. has seen increased focus on issues such as climate change and healthcare in recent elections": "real",
    "the state of Ohio has been a key bellwether state in presidential elections": "real",
    "the political landscape in the U.S. is shaped by both local and national issues": "real",
    "in 2020, several states expanded access to early voting and mail-in voting": "real",
    "the U.S. has a history of contentious Supreme Court nominations": "real",
    "the political parties in the U.S. have undergone significant transformations over the years": "real",
    "the state of Michigan played a pivotal role in the 2020 presidential election": "real",
    "the U.S. has a system of checks and balances that limits the power of each branch of government": "real",
    "in 2021, President Biden proposed a significant infrastructure plan to modernize U.S. transportation": "real",
    "the rise of digital campaigning has transformed the way candidates connect with voters": "real",
    "the state of Virginia has been a key battleground in recent elections": "real",
    "the U.S. has a long tradition of civic engagement and voter participation": "real",
    "the Supreme Court's decisions often reflect the political leanings of the justices": "real",
    "the U.S. has a vibrant history of political cartoons and satire reflecting public sentiment": "real",
    "the debate over healthcare remains a contentious issue in U.S. politics": "real",
    "the 2024 election is expected to have high stakes for both major parties": "real",
    "the use of technology in elections has raised concerns about security and integrity": "real",
    "the U.S. political system is characterized by a two-party system dominated by Democrats and Republicans": "real",
    "the political climate in the U.S. has seen increased division along ideological lines": "real",
    "the state of Arizona has been a focal point for discussions about voting access and election integrity": "real",
    "the political history of the U.S. includes numerous movements advocating for social justice": "real",
    "in recent elections, the youth vote has played a crucial role in determining outcomes": "real",
    "the process of gerrymandering has significant implications for political representation": "real",
    "the concept of checks and balances was designed to prevent any one branch of government from becoming too powerful": "real",
    "the 2024 election is anticipated to feature a diverse group of candidates": "real",
    "the U.S. has a rich history of debates and discussions around the First Amendment rights": "real",
    "the Supreme Court's ruling in Roe v. Wade in 1973 legalized abortion nationwide": "real",
    "in recent years, there has been a resurgence of interest in civic education and engagement": "real",
    "the political landscape is shaped by issues such as immigration, education, and healthcare": "real",
    "the U.S. has seen an increase in voter registration drives, particularly in marginalized communities": "real",
    "the influence of social media on elections continues to evolve and raise concerns": "real",
    "the U.S. has a history of political parties realigning based on social and economic changes": "real",
    "in 2022, many states proposed measures aimed at protecting voting rights": "real",
    "the state of Wisconsin has been a battleground for electoral disputes in recent years": "real",
    "the U.S. political system allows for significant state-level variation in laws and regulations": "real",
    "in 2024, many political analysts are closely watching key swing states for presidential election outcomes": "real",
    "the U.S. has seen increased grassroots activism in response to social and political issues": "real",
    "the debate over climate change policy remains a polarizing issue in American politics": "real",
    "the U.S. has a long tradition of civil liberties and the protection of individual rights": "real",
    "the state of New Hampshire is known for its role in the presidential primary process": "real",
    "the Electoral College system has been criticized for not reflecting the popular vote": "real",
    "the U.S. has experienced several instances of political realignment throughout its history": "real",
    "the role of the media in shaping public opinion has become increasingly significant in recent years": "real",
    "the debate over immigration reform continues to be a major issue in U.S. politics": "real",
    "the U.S. has seen a growing trend of voter mobilization efforts targeting young people": "real",
    "the influence of money in politics remains a contentious topic in American elections": "real",
    "the U.S. has a history of major political movements advocating for change, including the Civil Rights Movement": "real",
    "the state of Nevada is known for its early voting procedures and caucus system": "real",
    "the U.S. has seen a significant increase in women running for office in recent elections": "real",
    "the political landscape is shaped by both national and local issues that resonate with voters": "real",
    "in 2020, several states faced legal challenges related to voting procedures and election outcomes": "real",
    "the U.S. has a diverse political landscape with a variety of viewpoints and ideologies": "real",
    "the debate over healthcare reform continues to be a significant issue in political discourse": "real",
    "the U.S. political system is influenced by the interests of various lobby groups and organizations": "real",
    "the role of the U.S. in global politics has been a subject of debate for decades": "real",
    "the state of North Carolina has seen significant political shifts in recent elections": "real",
    "the influence of foreign entities in U.S. elections has raised concerns about national security": "real",
    "the U.S. has a history of political compromise and bipartisanship, though it's become less common recently": "real",
    "the 2020 election saw record voter turnout across demographic groups": "real",
    "the role of technology in shaping political discourse has become more pronounced in recent years": "real",
    "the state of Texas has been a significant player in national politics, especially in presidential elections": "real",
    "the U.S. has seen increased efforts to ensure election security and integrity in recent years": "real",
    "the debate over education policy has been a contentious issue in U.S. politics": "real",
    "the 2022 midterm elections saw high levels of voter engagement and turnout": "real",
    "the U.S. has a long-standing commitment to free speech, though it faces challenges in the digital age": "real",
    "the role of community organizations in mobilizing voters has been critical in recent elections": "real",
    "the political landscape in the U.S. is shaped by both local and national events and issues": "real",
    "the state of Florida has emerged as a key battleground in presidential elections": "real",
    "the influence of social media on public discourse continues to evolve and raise concerns": "real",
    "the U.S. has a history of third-party candidates impacting major elections": "real",
    "the role of minority voters has become increasingly important in shaping election outcomes": "real",
    "the U.S. political system is designed to promote representation and accountability": "real",
    "the debate over gun control remains a significant issue in American politics": "real",
    "the state of Pennsylvania has played a crucial role in recent presidential elections": "real",
    "the U.S. has seen increased scrutiny of election laws and procedures in recent years": "real",
    "the impact of climate change on public policy continues to be a contentious issue": "real",
    "the U.S. political system is characterized by a separation of powers among the legislative, executive, and judicial branches": "real",
    "the role of the federal government in education policy has been a topic of ongoing debate": "real",
    "the influence of grassroots organizations has grown in recent years, particularly among younger voters": "real",
    "the debate over abortion rights remains a polarizing issue in U.S. politics": "real",
    "the state of New York has been a significant player in national politics due to its population and economic influence": "real",
    "the U.S. has seen a rise in political polarization, affecting both parties and their constituents": "real",
    "the impact of the COVID-19 pandemic on the political landscape has been profound and long-lasting": "real",
    "the 2024 election cycle is expected to bring major shifts in party strategies and candidate platforms": "real",
    "the role of the Senate in confirming presidential appointments has become increasingly significant": "real",
    "the U.S. has a history of women and minority candidates breaking barriers in politics": "real",
    "the debate over campaign finance reform continues to be a significant issue in political discussions": "real",
    "the role of the judiciary in interpreting laws has been a critical aspect of American democracy": "real",
    "the U.S. political landscape is shaped by economic issues such as taxes and trade policies": "real",
    "the state of Illinois has a diverse electorate that reflects a range of political opinions and values": "real",
    "the influence of local politics on national issues has become more pronounced in recent years": "real",
    "the U.S. has seen increased voter turnout efforts aimed at marginalized communities": "real",
    "the debate over net neutrality and internet access has implications for future political engagement": "real",
    "the state of Georgia has been in the national spotlight for its voting laws and election outcomes": "real",
    "the U.S. has a history of political reform movements seeking to address systemic issues": "real",
    "the role of the electoral process in shaping public policy has been a significant focus of recent discussions": "real",
    "the debate over transportation infrastructure funding remains a contentious issue in U.S. politics": "real",
    "the U.S. has seen increased collaboration between grassroots movements and political parties": "real",
    "the impact of media coverage on election outcomes continues to be a subject of study and debate": "real",
    "the role of debates and public forums in shaping voter opinions is a critical aspect of the electoral process": "real",
    "the U.S. has seen significant shifts in public opinion on issues like healthcare and climate change": "real",
    "the state of Massachusetts has a rich political history and has been influential in shaping national policies": "real",
    "the U.S. political system encourages citizen participation through voting and advocacy": "real",
    "the debate over the role of big tech in politics continues to raise questions about accountability and transparency": "real",
    "the U.S. has a history of voter intimidation and suppression efforts that have shaped electoral outcomes": "real",
    "the role of women in politics has grown significantly, leading to more diverse representation in government": "real",
    "the impact of social movements on public policy continues to be a driving force in American politics": "real",
    "the U.S. has a long tradition of political engagement through protests and advocacy efforts": "real",
    "the debate over mental health policy has gained increased attention in recent years": "real",
    "the state of Colorado has been at the forefront of discussions about voting access and election integrity": "real",
    "the U.S. has seen a growing trend of political engagement among younger voters, particularly in urban areas": "real",
    "the influence of traditional media on public perception of political issues remains significant": "real",
    "the role of the presidency in shaping foreign policy has been a critical aspect of U.S. governance": "real",
    "the debate over the electoral process has led to calls for reforms and modernization in many states": "real",
    "the U.S. has seen a rise in community organizing efforts aimed at increasing voter participation": "real",
    "the impact of the pandemic on public health policy continues to influence political discussions": "real",
    "the role of the federal government in addressing climate change is a major point of contention in U.S. politics": "real",
    "the U.S. has a rich tradition of debate and discussion about civil rights and liberties": "real",
    "the debate over public transportation funding remains an important issue in many urban areas": "real",
    "the U.S. has seen increased advocacy for mental health resources and services in recent years": "real",
    "the role of civic education in promoting informed citizenship has gained renewed attention": "real",
    "the state of South Carolina has been influential in shaping national election outcomes due to its primary status": "real",
    "the U.S. political landscape is shaped by the interplay of local, state, and national issues": "real",
    "the influence of public opinion polls on political decision-making has become more pronounced": "real",
    "the role of environmental policy in shaping political discourse continues to be a critical focus": "real",
    "the U.S. has a history of political dissension and activism seeking to address societal issues": "real",
    "the debate over net neutrality has significant implications for access to information and online participation": "real",
    "the U.S. has seen increased discussions around the role of technology in democracy and voting": "real",
    "the state of Maryland has been a leader in implementing progressive policies at the state level": "real",
    "the U.S. has a long tradition of honoring and recognizing the contributions of civil rights leaders": "real",
    "the influence of advocacy groups on policy decisions has been a critical aspect of U.S. governance": "real",
    "the role of youth in shaping the future of politics has gained recognition in recent years": "real",
    "the U.S. has a diverse electorate that reflects a range of experiences and perspectives": "real",
    "the debate over public education funding remains a significant issue for many communities": "real",
    "the role of international relations in U.S. politics is often influenced by domestic considerations": "real",
    "the U.S. has seen increased collaboration between local governments and community organizations": "real",
    "the impact of historical events on current political discussions is a topic of ongoing analysis": "real",
    "the debate over the role of the military in politics continues to be a point of contention": "real",
    "the U.S. political system has been shaped by the contributions of various demographic groups throughout history": "real",
    "the state of Louisiana has a unique political culture that influences its governance and elections": "real",
    "the U.S. has a long tradition of civil service and public service as a career path": "real",
    "the role of corporate interests in shaping public policy remains a topic of significant discussion": "real",
    "the debate over the role of the judiciary in interpreting laws continues to be a critical focus": "real",
    "the U.S. has seen increased calls for transparency and accountability in government decision-making": "real",
    "the state of Alaska has unique political issues related to its geography and economy": "real",
    "the U.S. has a history of movements advocating for LGBTQ+ rights and equality": "real",
    "the influence of grassroots movements on policy change has become increasingly visible in recent years": "real",
    "the role of faith-based organizations in politics remains a significant aspect of American civic life": "real",
    "the debate over public health policy has gained prominence, especially in light of recent crises": "real",
    "the U.S. has seen a rise in political activism among young people seeking change": "real",
    "the impact of economic inequality on political discourse is a growing concern": "real",
    "the role of social media in shaping political narratives is increasingly complex and influential": "real",
    "the U.S. has a tradition of political satire and humor that plays a role in public discourse": "real",
    "the debate over immigration policy continues to be a polarizing issue in U.S. politics": "real",
    "the U.S. has seen increased focus on the intersection of race and politics in recent years": "real",
    "the influence of academic research on public policy is a topic of ongoing exploration": "real",
    "the role of civic engagement in strengthening democracy is widely recognized as essential": "real",
    "the U.S. has a history of political leaders emerging from grassroots movements and community activism": "real",
    "the debate over energy policy is shaped by both economic and environmental considerations": "real",
    "the U.S. has seen a growing trend of local governments taking action on climate change issues": "real",
    "the role of the arts in promoting social change is an important aspect of American culture": "real",
    "the U.S. has a long tradition of celebrating and honoring its veterans for their service": "real",
    "the debate over campaign strategies and tactics continues to evolve as technology changes": "real",
    "the U.S. has seen significant growth in independent voters who influence election outcomes": "real",
    "the role of women in leadership positions is increasingly recognized as vital for effective governance": "real",
    "the debate over the impact of economic policy on working families remains a critical issue": "real",
    "the U.S. has a history of foreign influence on domestic politics, particularly during elections": "real",
    "the state of New Jersey has a diverse political landscape shaped by its demographics": "real",
    "the U.S. has seen increased focus on mental health awareness and its impact on society": "real",
    "the debate over corporate responsibility in politics has gained traction in recent years": "real",
    "the U.S. has a long-standing commitment to addressing public health issues through policy": "real",
    "the role of journalism in holding government accountable is a cornerstone of democracy": "real",
    "the debate over public safety and policing practices continues to be a significant issue": "real",
    "the U.S. has seen a rise in community-led initiatives to address local challenges": "real",
    "the influence of family dynamics on voting behavior is an area of ongoing research": "real",
    "the role of diplomacy in shaping U.S. foreign relations is a critical aspect of governance": "real",
    "the U.S. has a rich tradition of supporting humanitarian efforts both domestically and abroad": "real",
    "the debate over reproductive rights remains a contentious issue with deep societal implications": "real",
    "the U.S. has a history of civil disobedience and protests advocating for change": "real",
    "the role of sports in uniting communities and promoting social justice is increasingly recognized": "real",
    "the U.S. has seen increased efforts to ensure access to clean water and sanitation for all": "real",
    "the debate over affordable housing and urban development continues to shape city politics": "real",
    "the role of technology in enhancing civic participation is a growing area of interest": "real",
    "the U.S. has a long-standing commitment to supporting education and lifelong learning": "real",
    "the influence of the business sector on political decision-making remains significant": "real",
    "the debate over the future of work and labor rights is shaping the economic landscape": "real",
    "the U.S. has seen increased discussions around universal basic income as a potential solution": "real",
    "the role of environmental justice in political discourse is gaining recognition and importance": "real",
    "the U.S. has a diverse array of political ideologies that influence its governance": "real",
    "the debate over the balance of power between federal and state governments is ongoing": "real",
    "the U.S. has a history of political challenges leading to reforms and systemic changes": "real",
    "the role of citizen activism in shaping policy outcomes is a critical aspect of democracy": "real",
    "the U.S. has seen a rise in the influence of data and analytics in political campaigns": "real",
    "the debate over the role of labor unions in politics is a significant issue for workers' rights": "real",
    "the U.S. has a rich history of artistic expression and its connection to social movements": "real",
    "the role of community health initiatives in promoting well-being is increasingly recognized": "real",
    "the U.S. has seen increased advocacy for equitable access to healthcare services": "real",
    "the debate over the role of science in policy decisions remains a critical issue": "real",
    "the U.S. has a diverse array of political representation, reflecting its multicultural society": "real",
    "the influence of social entrepreneurship on public policy is an area of growing interest": "real",
    "the role of philanthropy in addressing social issues is a significant aspect of American life": "real",
    "the U.S. has a long tradition of innovation and its impact on economic growth": "real",
    "the debate over the future of education policy is shaped by changing societal needs": "real",
    "the U.S. has seen increased focus on addressing systemic racism through policy changes": "real",
    "the role of community development in promoting economic growth is widely recognized": "real",
    "the U.S. has a rich tradition of storytelling that shapes its cultural identity": "real",
    "the debate over the role of public libraries in society remains a relevant issue": "real",
    "the U.S. has seen increased attention to climate resilience and adaptation strategies": "real",
    "the role of art in healing and community building is gaining recognition": "real",
    "the U.S. has a diverse array of political movements advocating for social justice": "real",
    "the debate over voting rights and access continues to shape political landscapes across the country": "real",
    "the U.S. has a long-standing commitment to ensuring equal access to education for all": "real",
    "the influence of cultural narratives on political behavior is a growing area of research": "real",
    "the role of local journalism in informing communities is increasingly critical": "real",
    "the U.S. has seen a rise in activism focusing on environmental sustainability and conservation": "real",
    "the debate over the impact of technology on job displacement is an important issue for the future": "real",
    "the U.S. has a history of legal challenges addressing civil rights and liberties": "real",
    "the role of social capital in fostering community resilience is a significant area of study": "real",
    "the U.S. has seen increased efforts to promote financial literacy among citizens": "real",
    "the debate over access to affordable childcare remains a pressing issue for many families": "real",
    "the U.S. has a rich tradition of celebrating cultural diversity through festivals and events": "real",
    "the role of the federal budget in shaping social programs is a key aspect of governance": "real",
    "the U.S. has a history of legislative efforts addressing healthcare access and affordability": "real",
    "the debate over the impact of sports on youth development is a growing area of interest": "real",
    "the U.S. has seen increased attention to the importance of early childhood education": "real",
    "the role of cooperative movements in promoting economic sustainability is gaining recognition": "real",
    "the U.S. has a diverse array of cultural expressions that reflect its complex history": "real",
    "the debate over immigration reform continues to shape national discussions and policies": "real",
    "the U.S. has a long-standing commitment to preserving historical landmarks and sites": "real",
    "the influence of local businesses on economic development is a critical focus for many communities": "real",
    "the role of sustainability in shaping future economic policies is increasingly relevant": "real",
    "the U.S. has seen increased discussions around racial equity and justice in recent years": "real",
    "the debate over the impact of digital technology on mental health is gaining attention": "real",
    "the U.S. has a history of grassroots movements advocating for environmental protections": "real",
    "the role of traditional media in shaping public narratives continues to evolve": "real",
    "the U.S. has seen significant growth in the number of independent political organizations": "real",
    "the debate over the balance of power between citizens and government is ongoing": "real",
    "the U.S. has a rich tradition of supporting artistic expression as a form of social commentary": "real",
    "the role of technology in enhancing civic engagement is a growing area of exploration": "real",
    "the U.S. has seen increased calls for criminal justice reform in recent years": "real",
    "the debate over the future of work in a digital economy is shaping policy discussions": "real",
    "the U.S. has a diverse array of voices contributing to public discourse and policy discussions": "real",
    "the role of culture in shaping national identity is a topic of ongoing exploration": "real",
    "the U.S. has a history of political engagement through community organizing and activism": "real",
    "the debate over women's rights and gender equality remains a critical issue": "real",
    "the U.S. has seen increased attention to mental health issues and their societal implications": "real",
    "the role of social movements in advancing civil rights has shaped U.S. history": "real",
    "the U.S. has a rich tradition of documentary filmmaking that addresses social issues": "real",
    "the debate over the role of faith in public life continues to be a significant topic": "real",
    "the U.S. has seen increased advocacy for youth involvement in politics and civic engagement": "real",
    "the role of public spaces in fostering community connections is widely recognized": "real",
    "the U.S. has a diverse array of organizations working towards social change and justice": "real",
    "the debate over the future of health care policy is shaped by evolving needs and challenges": "real",
    "the U.S. has a history of philanthropy addressing pressing social issues and needs": "real",
    "the role of women in the workforce is a significant area of study and discussion": "real",
    "the U.S. has seen increased recognition of the importance of mental health support in schools": "real",
    "the debate over the impact of climate change on public health is gaining attention": "real",
    "the U.S. has a tradition of community service and volunteerism as a civic duty": "real",
    "the role of social networks in shaping political beliefs is a growing area of interest": "real",
    "the U.S. has a rich history of social entrepreneurship aimed at addressing societal challenges": "real",
    "the debate over housing affordability and availability is a pressing concern for many Americans": "real",
    "the U.S. has seen increased focus on the role of youth in driving social change": "real",
    "the role of social justice in education is a critical aspect of contemporary discussions": "real",
    "the U.S. has a history of resistance movements advocating for marginalized communities": "real",
    "the debate over police reform continues to shape national conversations on public safety": "real",
    "the U.S. has seen a rise in awareness about the importance of environmental sustainability": "real",
    "the role of cultural heritage in shaping identity is widely recognized as significant": "real",
    "the U.S. has a long tradition of labor movements advocating for workers' rights": "real",
    "the debate over public funding for the arts continues to be a relevant issue": "real",
    "the U.S. has a history of technological advancements shaping economic landscapes": "real",
    "the role of community organizing in social movements is a critical aspect of U.S. history": "real",
    "the U.S. has seen increased attention to the role of media literacy in education": "real",
    "the debate over healthcare access and equity remains a pressing challenge": "real",
    "the U.S. has a diverse array of social movements advocating for various causes": "real",
    "the role of cultural competency in healthcare is a growing area of focus": "real",
    "the U.S. has a long-standing commitment to addressing food insecurity through policy": "real",
    "the debate over the impact of globalization on local economies is a significant concern": "real",
    "the U.S. has seen increased advocacy for climate action at all levels of government": "real",
    "the role of local governments in addressing community needs is increasingly important": "real",
    "the U.S. has a rich history of community activism that addresses social injustices": "real",
    "the debate over the impact of social media on political polarization is gaining attention": "real",
    "the U.S. has a tradition of supporting education as a fundamental right": "real",
    "the role of cultural institutions in fostering social cohesion is widely acknowledged": "real",
    "the U.S. has seen a rise in interdisciplinary approaches to tackling complex issues": "real",
    "the debate over women's health rights continues to shape policy discussions": "real",
    "the U.S. has a diverse array of perspectives influencing public policy": "real",
    "the role of intergenerational dialogue in shaping social change is gaining recognition": "real",
    "the U.S. has a long history of addressing poverty through social programs and initiatives": "real",
    "the debate over the role of social media in public health communication is significant": "real",
    "the U.S. has seen increased efforts to address systemic inequities in education": "real",
    "the role of partnerships between government and nonprofit organizations is increasingly recognized": "real",
    "the U.S. has a rich tradition of literature reflecting social and political issues": "real",
    "the debate over environmental policy continues to evolve as new challenges arise": "real",
    "the U.S. has seen significant growth in mental health advocacy and support services": "real",
    "the role of art in reflecting societal issues is a critical aspect of cultural discourse": "real",
    "the U.S. has a long-standing commitment to ensuring equitable access to technology": "real",
    "the debate over the future of journalism in a digital age is ongoing": "real",
    "the U.S. has seen increased attention to the role of youth in shaping policy": "real",
    "the role of social entrepreneurship in driving innovation is a growing area of interest": "real",
    "the U.S. has a diverse array of community-based organizations working for social change": "real",
    "the debate over gun control laws remains a contentious issue in American politics": "real",
    "the U.S. has a history of political engagement through community activism and advocacy": "real",
    "the role of public policy in addressing social determinants of health is significant": "real",
    "the U.S. has seen increased awareness of the importance of data privacy and security": "real",
    "the debate over the impact of social isolation on mental health is gaining attention": "real",
    "the U.S. has a tradition of using public art to address social issues and injustices": "real",
    "the role of international relations in shaping domestic policy is increasingly recognized": "real",
    "the U.S. has seen a rise in initiatives aimed at reducing food waste and promoting sustainability": "real",
    "the debate over environmental justice and equity continues to shape policy discussions": "real",
    "the U.S. has a rich history of advocacy for civil rights and social justice": "real",
    "the role of science and technology in addressing global challenges is a significant topic": "real",
    "the U.S. has seen increased recognition of the importance of mental health in schools": "real",
    "the debate over public health policy in response to pandemics is a critical issue": "real",
    "the U.S. has a diverse array of voices contributing to the national conversation on social change": "real",
    "the role of community health workers in promoting wellness is gaining recognition": "real",
    "the U.S. has a long-standing commitment to supporting arts education in schools": "real",
    "the debate over immigration policy and its impact on families is a pressing concern": "real",
    "the U.S. has seen increased calls for racial justice and equity in recent years": "real",
    "the role of corporate social responsibility in shaping public perception is significant": "real",
    "the U.S. has a history of addressing environmental issues through policy changes": "real",
    "the debate over voting access and voter suppression remains a critical issue": "real",
    "the U.S. has seen significant growth in mental health services in response to community needs": "real",
    "the role of youth activism in shaping policy is a significant focus for many organizations": "real",
    "the U.S. has a rich tradition of public scholarship addressing social issues": "real",
    "the debate over the impact of media bias on public opinion is a relevant concern": "real",
    "the U.S. has seen increased recognition of the importance of affordable housing for all": "real",
    "the role of sports in promoting social inclusion and diversity is gaining attention": "real",
    "the U.S. has a long history of community organizing aimed at promoting social justice": "real",
    "the debate over the role of arts funding in society continues to evolve": "real",
    "the U.S. has a diverse array of grassroots movements advocating for various causes": "real",
    "the role of public policy in shaping environmental sustainability is increasingly significant": "real",
    "the U.S. has seen increased efforts to promote healthy lifestyles and nutrition": "real",
    "the debate over the role of technology in education continues to shape discussions on pedagogy": "real",
    "the U.S. has a history of philanthropy supporting education and innovation": "real",
    "the role of social media in shaping public health messaging is gaining attention": "real",
    "the U.S. has a rich tradition of environmental activism addressing pressing challenges": "real",
    "the debate over corporate influence in politics remains a contentious issue": "real",
    "the U.S. has seen a rise in initiatives promoting financial literacy and economic empowerment": "real",
    "the role of ethics in public service is a significant area of discussion": "real",
    "the U.S. has a long-standing commitment to addressing the needs of marginalized communities": "real",
    "the debate over the future of work in the gig economy is a growing concern": "real",
    "the U.S. has seen increased recognition of the importance of diversity in leadership": "real",
    "the role of the arts in fostering community resilience is gaining recognition": "real",
    "the U.S. has a diverse array of cultural expressions reflecting its complex history": "real",
    "the debate over public transportation and infrastructure remains a significant issue": "real",
    "the U.S. has seen increased advocacy for comprehensive immigration reform": "real",
    "the role of youth voices in policy discussions is increasingly recognized as vital": "real",
    "the U.S. has a long tradition of public service as a means of effecting change": "real",
    "the debate over food justice and access to healthy foods continues to evolve": "real",
    "the U.S. has seen significant changes in attitudes towards mental health in recent years": "real",
    "the role of public health campaigns in addressing social issues is critical": "real",
    "the U.S. has a history of addressing economic disparities through policy initiatives": "real",
    "the debate over privacy rights in the digital age is a pressing concern": "real",
    "the U.S. has seen increased recognition of the importance of emotional intelligence in leadership": "real",
    "the role of interdisciplinary collaboration in addressing complex challenges is gaining attention": "real",
    "the U.S. has a rich history of community-led initiatives aimed at social improvement": "real",
    "the debate over racial equity in education continues to shape policy discussions": "real",
    "the U.S. has seen increased advocacy for affordable healthcare options": "real",
    "the role of civic education in fostering informed citizenry is widely acknowledged": "real",
    "the U.S. has a long-standing commitment to civil liberties and social justice": "real",
    "the debate over the impact of technology on job creation is a relevant concern": "real",
    "the U.S. has seen significant growth in online education and its accessibility": "real",
    "the role of cultural representation in media is a critical area of focus": "real",
    "the U.S. has a diverse array of organizations advocating for environmental sustainability": "real",
    "the debate over the role of government in regulating business practices is ongoing": "real",
    "the U.S. has seen increased awareness of the impact of climate change on communities": "real",
    "the role of community gardens in promoting food security is widely recognized": "real",
    "the U.S. has a history of addressing the needs of individuals with disabilities through policy": "real",
    "the debate over the role of technology in education is a growing topic of discussion": "real",
    "the U.S. has seen a rise in initiatives aimed at promoting mental health awareness": "real",
    "the role of personal stories in advocacy is gaining recognition as an effective tool": "real",
    "the U.S. has a long tradition of collective action for social justice": "real",
    "the debate over public funding for education continues to be a contentious issue": "real",
    "the U.S. has seen increased advocacy for equitable access to public resources": "real",
    "the role of youth-led movements in driving change is increasingly acknowledged": "real",
    "the U.S. has a diverse array of faith-based organizations working for social good": "real",
    "the debate over the influence of money in politics remains a significant concern": "real",
    "the U.S. has a history of using public policy to address health disparities": "real",
    "the role of volunteerism in strengthening communities is widely recognized": "real",
    "the U.S. has seen significant changes in public attitudes towards immigration": "real",
    "the debate over corporate responsibility in addressing social issues is ongoing": "real",
    "the U.S. has a rich tradition of journalism advocating for social justice and accountability": "real",
    "the role of cultural competency in healthcare is increasingly recognized as vital": "real",
    "the U.S. has seen a rise in community-led efforts to address environmental challenges": "real",
    "the debate over access to mental health services remains a pressing issue": "real",
    "the U.S. has a long-standing commitment to promoting gender equity and rights": "real",
    "the role of social media in shaping public discourse is a significant area of study": "real",
    "the U.S. has a diverse array of approaches to address educational inequities": "real",
    "the debate over the impact of artificial intelligence on employment is a growing concern": "real",
    "the U.S. has seen increased recognition of the importance of community engagement in governance": "real",
    "the role of public-private partnerships in addressing social challenges is increasingly important": "real",
    "the U.S. has a history of supporting grassroots organizing for social change": "real",
    "the debate over the impact of climate change on national security is gaining attention": "real",
    "the U.S. has seen significant growth in initiatives aimed at supporting veterans": "real",
    "the role of education in promoting civic responsibility is widely recognized": "real",
    "the U.S. has a long tradition of arts education promoting social awareness": "real",
    "the debate over economic inequality and its impact on society continues to be relevant": "real",
    "the U.S. has seen increased advocacy for the rights of marginalized communities": "real",
    "the role of public health infrastructure in addressing crises is critical": "real",
    "the U.S. has a diverse array of organizations dedicated to promoting social equity": "real",
    "the debate over access to affordable housing remains a pressing challenge": "real",
    "the U.S. has seen significant growth in initiatives aimed at reducing homelessness": "real",
    "the role of cultural diversity in shaping society is increasingly acknowledged": "real",
    "the U.S. has a rich history of art reflecting social movements and issues": "real",
    "the debate over the role of technology in shaping democracy is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of environmental education": "real",
    "the role of advocacy in influencing public policy is a significant area of focus": "real",
    "the U.S. has a long-standing commitment to transparency and accountability in governance": "real",
    "the debate over the influence of lobbyists on policy decisions remains a concern": "real",
    "the U.S. has seen a rise in awareness about the importance of mental health in workplaces": "real",
    "the role of family in shaping individual experiences is a critical area of study": "real",
    "the U.S. has a diverse array of educational approaches addressing social challenges": "real",
    "the debate over the impact of automation on the workforce is a pressing issue": "real",
    "the U.S. has a history of addressing public health issues through community engagement": "real",
    "the role of storytelling in fostering social change is gaining recognition": "real",
    "the U.S. has seen significant changes in public attitudes towards mental health treatment": "real",
    "the debate over the effectiveness of welfare programs continues to be discussed": "real",
    "the U.S. has a rich tradition of public art addressing social justice issues": "real",
    "the role of nonprofit organizations in addressing community needs is widely acknowledged": "real",
    "the U.S. has a long-standing commitment to ensuring the rights of individuals with disabilities": "real",
    "the debate over the role of government in addressing poverty is ongoing": "real",
    "the U.S. has seen increased advocacy for LGBTQ+ rights and recognition": "real",
    "the role of mentorship in fostering personal and professional development is significant": "real",
    "the U.S. has a diverse array of voices contributing to the arts and cultural discourse": "real",
    "the debate over the impact of technology on education equity remains a relevant issue": "real",
    "the U.S. has seen a rise in initiatives aimed at promoting arts education": "real",
    "the role of grassroots activism in shaping policy is increasingly recognized": "real",
    "the U.S. has a history of addressing public health crises through innovative solutions": "real",
    "the debate over the future of social security and retirement benefits is ongoing": "real",
    "the U.S. has seen significant growth in community resilience initiatives in response to crises": "real",
    "the role of digital literacy in education is gaining recognition as essential": "real",
    "the U.S. has a long tradition of supporting cultural heritage preservation": "real",
    "the debate over the role of philanthropy in addressing social issues is a significant topic": "real",
    "the U.S. has seen increased recognition of the importance of arts in education": "real",
    "the role of interdisciplinary approaches in tackling global challenges is widely acknowledged": "real",
    "the U.S. has a diverse array of organizations focused on promoting environmental justice": "real",
    "the debate over the role of the federal government in regulating industries remains contentious": "real",
    "the U.S. has seen increased advocacy for universal basic income as a solution to poverty": "real",
    "the role of public discourse in shaping societal norms is a critical area of study": "real",
    "the U.S. has a history of addressing the needs of veterans through policy initiatives": "real",
    "the debate over the impact of foreign policy on domestic issues is ongoing": "real",
    "the U.S. has seen significant changes in public attitudes towards climate action": "real",
    "the role of social movements in influencing public policy is widely recognized": "real",
    "the U.S. has a long-standing commitment to protecting civil liberties and human rights": "real",
    "the debate over the future of the gig economy and workers' rights is gaining attention": "real",
    "the U.S. has seen increased recognition of the importance of health equity in policymaking": "real",
    "the role of community engagement in public health is gaining prominence": "real",
    "the U.S. has a rich tradition of storytelling as a tool for social change": "real",
    "the debate over access to quality education for all continues to be a pressing concern": "real",
    "the U.S. has seen significant advocacy for policies promoting racial equity": "real",
    "the role of community coalitions in addressing social issues is widely acknowledged": "real",
    "the U.S. has a history of using public art as a means of activism": "real",
    "the debate over the role of ethics in business practices remains relevant": "real",
    "the U.S. has seen a rise in awareness of the importance of civic engagement": "real",
    "the role of technology in enhancing educational access is a significant area of exploration": "real",
    "the U.S. has a diverse array of community-led initiatives aimed at promoting social change": "real",
    "the debate over the effectiveness of economic stimulus measures is ongoing": "real",
    "the U.S. has seen increased advocacy for policies that support working families": "real",
    "the role of public health education in preventing disease is critical": "real",
    "the U.S. has a long tradition of fostering innovation in technology and research": "real",
    "the debate over the impact of social media on mental health is a growing concern": "real",
    "the U.S. has seen significant growth in efforts to address homelessness": "real",
    "the role of cultural institutions in promoting social dialogue is increasingly recognized": "real",
    "the U.S. has a diverse array of organizations working to support refugees and immigrants": "real",
    "the debate over the future of healthcare policy remains a pressing issue": "real",
    "the U.S. has seen increased recognition of the importance of mental health in the workplace": "real",
    "the role of youth activism in shaping public policy is gaining attention": "real",
    "the U.S. has a history of addressing health disparities through targeted initiatives": "real",
    "the debate over environmental regulations and their impact on business is ongoing": "real",
    "the U.S. has seen significant changes in public perceptions of climate change": "real",
    "the role of empathy in leadership is widely acknowledged as essential": "real",
    "the U.S. has a long-standing commitment to advancing educational opportunities for all": "real",
    "the debate over the impact of technology on privacy rights is a pressing concern": "real",
    "the U.S. has seen increased advocacy for policies promoting gender equity in the workplace": "real",
    "the role of nonprofit organizations in providing social services is critical": "real",
    "the U.S. has a rich history of grassroots organizing for social change": "real",
    "the debate over public funding for the arts remains a contentious issue": "real",
    "the U.S. has seen a rise in community-led initiatives to promote health and wellness": "real",
    "the role of public spaces in fostering community engagement is increasingly recognized": "real",
    "the U.S. has a diverse array of voices contributing to the dialogue on social justice": "real",
    "the debate over the impact of immigration on the economy is ongoing": "real",
    "the U.S. has seen significant advocacy for environmental protection policies": "real",
    "the role of personal finance education in promoting economic stability is gaining attention": "real",
    "the U.S. has a long tradition of using art as a means of social commentary": "real",
    "the debate over the effectiveness of social welfare programs is a pressing concern": "real",
    "the U.S. has seen increased recognition of the importance of mental health support services": "real",
    "the role of historical context in shaping current social issues is critical": "real",
    "the U.S. has a diverse array of organizations dedicated to promoting social and economic justice": "real",
    "the debate over the future of public transportation continues to be relevant": "real",
    "the U.S. has seen significant growth in efforts to address food insecurity": "real",
    "the role of technology in enhancing accessibility for individuals with disabilities is crucial": "real",
    "the U.S. has a history of advocating for workers' rights through collective action": "real",
    "the debate over the impact of climate change on public health is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of community-based healthcare": "real",
    "the role of education in promoting social cohesion is widely acknowledged": "real",
    "the U.S. has a long-standing commitment to supporting public education initiatives": "real",
    "the debate over the influence of social media on political discourse is significant": "real",
    "the U.S. has seen significant changes in public attitudes towards environmental conservation": "real",
    "the role of cultural exchange in fostering understanding is increasingly recognized": "real",
    "the U.S. has a diverse array of initiatives aimed at promoting social equity": "real",
    "the debate over the effectiveness of law enforcement practices continues to be discussed": "real",
    "the U.S. has seen a rise in awareness about the impact of poverty on education": "real",
    "the role of social services in supporting individuals and families is critical": "real",
    "the U.S. has a rich tradition of using theater as a form of activism": "real",
    "the debate over the future of energy policy is a pressing concern": "real",
    "the U.S. has seen increased advocacy for mental health awareness and resources": "real",
    "the role of personal narratives in shaping public understanding is significant": "real",
    "the U.S. has a long-standing commitment to addressing systemic inequalities": "real",
    "the debate over public health responses to crises is ongoing": "real",
    "the U.S. has seen significant changes in public attitudes towards vaccination": "real",
    "the role of community-led disaster response is gaining recognition as essential": "real",
    "the U.S. has a diverse array of organizations focused on promoting educational equity": "real",
    "the debate over the impact of incarceration on communities continues to be relevant": "real",
    "the U.S. has seen increased recognition of the importance of affordable housing": "real",
    "the role of interdisciplinary collaboration in addressing societal challenges is critical": "real",
    "the U.S. has a history of advocating for environmental justice and sustainability": "real",
    "the debate over the influence of advertising on consumer behavior is ongoing": "real",
    "the U.S. has seen significant advocacy for policies supporting the rights of children": "real",
    "the role of public policy in shaping economic opportunity is widely acknowledged": "real",
    "the U.S. has a rich history of cultural contributions from diverse communities": "real",
    "the debate over the future of the education system remains a pressing issue": "real",
    "the U.S. has seen increased awareness about the importance of digital rights": "real",
    "the role of social enterprises in addressing social issues is gaining recognition": "real",
    "the U.S. has a long tradition of supporting mental health initiatives through policy": "real",
    "the debate over the effectiveness of educational reforms continues to be discussed": "real",
    "the U.S. has seen significant growth in community engagement efforts in recent years": "real",
    "the role of storytelling in public policy advocacy is increasingly acknowledged": "real",
    "the U.S. has a diverse array of organizations dedicated to promoting peace and justice": "real",
    "the debate over the impact of climate change on vulnerable populations is ongoing": "real",
    "the U.S. has seen increased advocacy for restorative justice practices": "real",
    "the role of transparency in government is widely recognized as essential": "real",
    "the U.S. has a history of using data-driven approaches to address social issues": "real",
    "the debate over the future of labor rights remains a significant topic": "real",
    "the U.S. has seen significant changes in public attitudes towards mental health treatment": "real",
    "the role of youth involvement in social change is increasingly recognized": "real",
    "the U.S. has a long-standing commitment to fostering diversity and inclusion in all sectors": "real",
    "the debate over the role of education in promoting economic mobility is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of mental health resources in schools": "real",
    "the role of public health initiatives in addressing social determinants of health is critical": "real",
    "the U.S. has a diverse array of organizations focused on supporting marginalized communities": "real",
    "the debate over the effectiveness of criminal justice reform is a pressing concern": "real",
    "the U.S. has seen significant growth in initiatives aimed at promoting equity in healthcare": "real",
    "the role of cultural institutions in fostering community dialogue is increasingly acknowledged": "real",
    "the U.S. has a rich history of using literature as a means of social critique": "real",
    "the debate over the future of public health policy remains a relevant issue": "real",
    "the U.S. has seen increased recognition of the importance of social determinants of health": "real",
    "the role of intersectionality in social justice movements is gaining attention": "real",
    "the U.S. has a long tradition of civic engagement and public service": "real",
    "the debate over the impact of economic policies on social welfare is ongoing": "real",
    "the U.S. has seen significant advocacy for policies addressing food insecurity": "real",
    "the role of educational access in promoting social mobility is widely acknowledged": "real",
    "the U.S. has a diverse array of initiatives aimed at supporting marginalized populations": "real",
    "the debate over the effectiveness of climate change policies is ongoing": "real",
    "the U.S. has seen significant growth in community-based mental health services": "real",
    "the role of social justice education in schools is increasingly recognized": "real",
    "the U.S. has a history of advocating for environmental sustainability through legislation": "real",
    "the debate over the influence of social media on youth behavior is a pressing concern": "real",
    "the U.S. has seen increased awareness of the importance of supporting small businesses": "real",
    "the role of philanthropy in addressing social issues is critical": "real",
    "the U.S. has a long-standing commitment to addressing the needs of underserved communities": "real",
    "the debate over the future of public education remains a topic of discussion": "real",
    "the U.S. has seen significant changes in public attitudes towards climate change": "real",
    "the role of social innovation in addressing community needs is gaining recognition": "real",
    "the U.S. has a rich history of using music as a form of social expression": "real",
    "the debate over the impact of foreign aid on global development is ongoing": "real",
    "the U.S. has seen increased advocacy for equitable access to technology": "real",
    "the role of community gardens in promoting food security is increasingly recognized": "real",
    "the U.S. has a history of using data to drive social change": "real",
    "the debate over the effectiveness of youth programs continues to be discussed": "real",
    "the U.S. has seen significant growth in awareness about the importance of mental health for all": "real",
    "the role of grassroots movements in shaping public policy is critical": "real",
    "the U.S. has a diverse array of organizations dedicated to promoting education for all": "real",
    "the debate over the future of the social safety net is a pressing issue": "real",
    "the U.S. has seen increased recognition of the importance of accessibility in public spaces": "real",
    "the role of advocacy in advancing social change is widely acknowledged": "real",
    "the U.S. has a long tradition of using storytelling to promote social justice": "real",
    "the debate over the influence of political lobbying on policy decisions is ongoing": "real",
    "the U.S. has seen significant changes in public perceptions of immigration": "real",
    "the role of civic education in promoting informed citizenship is crucial": "real",
    "the U.S. has a rich history of using art as a means of protest": "real",
    "the debate over the effectiveness of gun control measures continues to be discussed": "real",
    "the U.S. has seen increased advocacy for policies supporting family caregivers": "real",
    "the role of technology in promoting remote work is widely recognized": "real",
    "the U.S. has a long-standing commitment to fostering economic opportunity for all": "real",
    "the debate over the impact of climate change on agriculture is ongoing": "real",
    "the U.S. has seen significant growth in initiatives aimed at promoting digital literacy": "real",
    "the role of public transportation in promoting social equity is gaining recognition": "real",
    "the U.S. has a diverse array of organizations focused on environmental conservation": "real",
    "the debate over the effectiveness of youth mentorship programs is ongoing": "real",
    "the U.S. has seen increased awareness about the importance of disaster preparedness": "real",
    "the role of community health workers in promoting wellness is critical": "real",
    "the U.S. has a history of advocating for the rights of people with disabilities": "real",
    "the debate over the influence of celebrity culture on public opinion is significant": "real",
    "the U.S. has seen significant advocacy for equitable access to healthcare": "real",
    "the role of community engagement in fostering resilience is increasingly recognized": "real",
    "the U.S. has a long tradition of supporting the arts as a means of expression": "real",
    "the debate over the impact of climate change on economic inequality is ongoing": "real",
    "the U.S. has seen significant growth in the awareness of mental health issues": "real",
    "the role of education in promoting critical thinking is widely acknowledged": "real",
    "the U.S. has a diverse array of organizations dedicated to fostering social change": "real",
    "the debate over the future of technology regulation remains a pressing concern": "real",
    "the U.S. has seen increased advocacy for policies addressing racial disparities": "real",
    "the role of youth in shaping policy agendas is increasingly recognized": "real",
    "the U.S. has a history of using public art to address social issues": "real",
    "the debate over the effectiveness of international aid is ongoing": "real",
    "the U.S. has seen significant growth in community-led initiatives for social justice": "real",
    "the role of public policy in addressing climate change is crucial": "real",
    "the U.S. has a long-standing commitment to promoting cultural diversity": "real",
    "the debate over the impact of globalization on local economies is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of mental health support in schools": "real",
    "the role of social media in mobilizing social movements is critical": "real",
    "the U.S. has a rich history of using spoken word as a form of activism": "real",
    "the debate over the effectiveness of family support programs continues to be discussed": "real",
    "the U.S. has seen significant advocacy for environmental justice initiatives": "real",
    "the role of historical context in understanding current events is widely acknowledged": "real",
    "the U.S. has a diverse array of organizations dedicated to advancing women's rights": "real",
    "the debate over the impact of the gig economy on workers' rights is ongoing": "real",
    "the U.S. has seen increased awareness about the importance of affordable childcare": "real",
    "the role of civic engagement in promoting social cohesion is critical": "real",
    "the U.S. has a long tradition of grassroots activism for social change": "real",
    "the debate over the effectiveness of international treaties on climate change is ongoing": "real",
    "the U.S. has seen significant growth in awareness about the importance of public health": "real",
    "the role of environmental education in promoting sustainability is widely recognized": "real",
    "the U.S. has a rich history of using film as a medium for social commentary": "real",
    "the debate over the impact of digital surveillance on privacy is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of representation in media": "real",
    "the role of food sovereignty in promoting community health is critical": "real",
    "the U.S. has a history of advocating for voting rights through legislation": "real",
    "the debate over the effectiveness of rehabilitation programs in prisons is ongoing": "real",
    "the U.S. has seen significant advocacy for policies addressing mental health in the workplace": "real",
    "the role of intersectionality in understanding social issues is gaining recognition": "real",
    "the U.S. has a long-standing commitment to fostering social cohesion through community programs": "real",
    "the debate over the impact of economic inequality on social mobility is significant": "real",
    "the U.S. has seen increased advocacy for policies promoting racial justice": "real",
    "the role of community organizing in addressing local issues is widely recognized": "real",
    "the U.S. has a diverse array of initiatives aimed at promoting environmental sustainability": "real",
    "the debate over the effectiveness of public health campaigns is ongoing": "real",
    "the U.S. has seen significant growth in awareness about the importance of mental health resources": "real",
    "the role of storytelling in fostering empathy is critical": "real",
    "the U.S. has a rich tradition of using poetry as a means of social critique": "real",
    "the debate over the influence of corporate interests on public policy is significant": "real",
    "the U.S. has seen increased advocacy for equitable access to education": "real",
    "the role of community service in promoting civic engagement is increasingly recognized": "real",
    "the U.S. has a long-standing commitment to advancing social and economic rights": "real",
    "the debate over the effectiveness of public health initiatives in reducing health disparities is ongoing": "real",
    "the U.S. has seen significant changes in public perceptions of social justice movements": "real",
    "the role of youth leadership in promoting social change is widely acknowledged": "real",
    "the U.S. has a diverse array of organizations dedicated to promoting economic equity": "real",
    "the debate over the impact of healthcare policy on social outcomes remains relevant": "real",
    "the U.S. has seen increased recognition of the importance of social safety nets": "real",
    "the role of diversity in enriching community life is critical": "real",
    "the U.S. has a history of advocating for the rights of workers through unionization": "real",
    "the debate over the effectiveness of education funding reforms is ongoing": "real",
    "the U.S. has seen significant growth in awareness about the impact of environmental policies on public health": "real",
    "the role of public discourse in shaping community values is increasingly recognized": "real",
    "the U.S. has a rich tradition of using music as a tool for social activism": "real",
    "the debate over the influence of social norms on behavior is significant": "real",
    "the U.S. has seen increased advocacy for mental health education in schools": "real",
    "the role of technology in addressing societal challenges is critical": "real",
    "the U.S. has a long-standing commitment to fostering inclusivity in education": "real",
    "the debate over the impact of public funding on arts and culture is ongoing": "real",
    "the U.S. has seen significant advocacy for policies promoting environmental conservation": "real",
    "the role of cross-sector collaboration in addressing complex social issues is gaining recognition": "real",
    "the U.S. has a diverse array of organizations dedicated to promoting social entrepreneurship": "real",
    "the debate over the effectiveness of economic stimulus measures continues to be discussed": "real",
    "the U.S. has seen increased awareness about the importance of affordable housing": "real",
    "the role of restorative justice in promoting community healing is critical": "real",
    "the U.S. has a history of advocating for the rights of marginalized groups": "real",
    "the debate over the impact of media literacy on public opinion is significant": "real",
    "the U.S. has seen significant advocacy for policies addressing climate justice": "real",
    "the role of faith-based organizations in promoting social justice is increasingly recognized": "real",
    "the U.S. has a rich tradition of using visual art as a form of protest": "real",
    "the debate over the effectiveness of economic sanctions on foreign policy is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of cultural competence in healthcare": "real",
    "the role of grassroots organizing in promoting social change is critical": "real",
    "the U.S. has a diverse array of initiatives aimed at promoting mental health awareness": "real",
    "the debate over the impact of gentrification on community identity is significant": "real",
    "the U.S. has seen significant growth in awareness about the importance of food security": "real",
    "the role of public-private partnerships in addressing social challenges is gaining recognition": "real",
    "the U.S. has a long-standing commitment to advancing environmental justice initiatives": "real",
    "the debate over the effectiveness of international cooperation on climate change remains relevant": "real",
    "the U.S. has seen increased advocacy for equitable access to clean water": "real",
    "the role of art in promoting social cohesion is widely acknowledged": "real",
    "the U.S. has a history of using literature as a form of social commentary": "real",
    "the debate over the impact of economic policy on inequality is ongoing": "real",
    "the U.S. has seen significant growth in initiatives aimed at promoting youth empowerment": "real",
    "the role of public health in addressing social determinants of health is critical": "real",
    "the U.S. has a diverse array of organizations dedicated to promoting social welfare": "real",
    "the debate over the effectiveness of crime prevention programs is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of mental health support in communities": "real",
    "the role of community-led initiatives in promoting resilience is increasingly recognized": "real",
    "the U.S. has a rich history of using spoken word to address social issues": "real",
    "the debate over the influence of technology on interpersonal relationships is significant": "real",
    "the U.S. has seen significant advocacy for policies promoting gender equality": "real",
    "the role of policy advocacy in advancing social justice is critical": "real",
    "the U.S. has a long tradition of supporting community development initiatives": "real",
    "the debate over the impact of public policy on health outcomes remains relevant": "real",
    "the U.S. has seen increased awareness about the importance of social connections": "real",
    "the role of education in promoting civic engagement is widely recognized": "real",
    "the U.S. has a diverse array of organizations dedicated to addressing youth homelessness": "real",
    "the debate over the effectiveness of transitional housing programs is ongoing": "real",
    "the U.S. has seen significant growth in initiatives aimed at promoting community cohesion": "real",
    "the role of urban planning in addressing social equity is increasingly acknowledged": "real",
    "the U.S. has a history of advocating for the rights of children through legislation": "real",
    "the debate over the impact of social media on mental health is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of early childhood education": "real",
    "the role of community involvement in promoting public safety is critical": "real",
    "the U.S. has a rich tradition of using theater as a means of social critique": "real",
    "the debate over the effectiveness of restorative practices in schools is ongoing": "real",
    "the U.S. has seen significant advocacy for policies addressing homelessness": "real",
    "the role of community-based organizations in promoting health equity is increasingly recognized": "real",
    "the U.S. has a diverse array of initiatives aimed at fostering economic development": "real",
    "the debate over the impact of housing policy on social stability is significant": "real",
    "the U.S. has seen increased awareness about the importance of affordable healthcare": "real",
    "the role of public policy in promoting gender equality is critical": "real",
    "the U.S. has a long-standing commitment to addressing the needs of marginalized communities": "real",
    "the debate over the effectiveness of early intervention programs is ongoing": "real",
    "the U.S. has seen significant growth in initiatives aimed at promoting community health": "real",
    "the role of local government in addressing social issues is increasingly acknowledged": "real",
    "the U.S. has a history of advocating for the rights of LGBTQ+ individuals through legislation": "real",
    "the debate over the impact of mass incarceration on communities is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of financial literacy education": "real",
    "the role of community health initiatives in promoting wellness is critical": "real",
    "the U.S. has a rich tradition of using dance as a means of cultural expression": "real",
    "the debate over the effectiveness of after-school programs in supporting youth development is ongoing": "real",
    "the U.S. has seen significant advocacy for policies promoting accessibility for people with disabilities": "real",
    "the role of public discourse in fostering social understanding is widely recognized": "real",
    "the U.S. has a diverse array of organizations dedicated to advancing civil rights": "real",
    "the debate over the impact of climate change on public health remains a pressing issue": "real",
    "the U.S. has seen increased advocacy for equitable access to public spaces": "real",
    "the role of community support networks in promoting resilience is critical": "real",
    "the U.S. has a long-standing commitment to fostering inclusivity in the workplace": "real",
    "the debate over the effectiveness of environmental policies in mitigating climate change is ongoing": "real",
    "the U.S. has seen significant growth in initiatives aimed at promoting digital equity": "real",
    "the role of community gardens in promoting mental health is increasingly recognized": "real",
    "the U.S. has a history of using advocacy to advance labor rights": "real",
    "the debate over the impact of wealth inequality on social mobility is significant": "real",
    "the U.S. has seen increased recognition of the importance of family support services": "real",
    "the role of storytelling in preserving cultural heritage is critical": "real",
    "the U.S. has a diverse array of initiatives aimed at promoting social equity": "real",
    "the debate over the effectiveness of public transportation systems is ongoing": "real",
    "the U.S. has seen significant growth in awareness about the importance of climate resilience": "real",
    "the role of education in promoting environmental sustainability is widely acknowledged": "real",
    "the U.S. has a rich tradition of using visual art to convey social messages": "real",
    "the debate over the influence of corporate lobbying on legislation is significant": "real",
    "the U.S. has seen increased advocacy for mental health services in schools": "real",
    "the role of youth activism in shaping policy is increasingly recognized": "real",
    "the U.S. has a long-standing commitment to addressing income inequality through policy reforms": "real",
    "the debate over the impact of digital communication on interpersonal relationships is ongoing": "real",
    "the U.S. has seen significant growth in initiatives aimed at promoting gender equity": "real",
    "the role of environmental policy in promoting sustainable development is critical": "real",
    "the U.S. has a diverse array of organizations dedicated to supporting mental health initiatives": "real",
    "the debate over the effectiveness of public health infrastructure is ongoing": "real",
    "the U.S. has seen increased recognition of the importance of affordable housing policies": "real",
    "the role of local communities in addressing food insecurity is widely acknowledged": "real",
    "the U.S. has a history of advocating for civil rights through grassroots movements": "real",
    "the debate over the impact of economic policy on public health outcomes is significant": "real",
    "the U.S. has seen significant advocacy for policies promoting community development": "real",
    "the role of public participation in the policy-making process is critical": "real",
    "the U.S. has a long-standing commitment to addressing climate change through legislative action": "real",
    "the debate over the effectiveness of social programs in reducing poverty is ongoing": "real",
    "the U.S. has seen increased awareness about the importance of workplace diversity": "real",
    "the role of education in promoting civic responsibility is widely recognized": "real",
    "in 2022, the U.S. saw the highest number of state-level ballot measures in a decade": "real",
    "the U.S. Congress consists of two chambers: the Senate and the House of Representatives": "real",
    "the President must be at least 35 years old to hold office": "real",
    "the 22nd Amendment limits U.S. presidents to two terms": "real",
    "the Vice President serves as the President of the Senate but votes only in case of a tie": "real",
    "the 19th Amendment gave women the right to vote in 1920": "real",
    "the Tea Party movement began as a protest against high taxes and government spending in 2009": "real",
    "the 13th Amendment abolished slavery in the United States": "real",
    "the U.S. Constitution's First Amendment protects freedom of speech and religion": "real"
    // Add more facts here following the same format
};